// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReboteqTask.Infrastructure.Data;

#nullable disable

namespace ReboteqTask.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241211224556_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReboteqTask.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "COUPON-T0PI9V",
                            Discount = 27.20511555840400m
                        },
                        new
                        {
                            Id = 2,
                            Code = "COUPON-ITSOP5",
                            Discount = 24.050513738076900m
                        },
                        new
                        {
                            Id = 3,
                            Code = "COUPON-GC2592",
                            Discount = 7.1857321456225550m
                        },
                        new
                        {
                            Id = 4,
                            Code = "COUPON-DLKM69",
                            Discount = 5.2952985863887775m
                        },
                        new
                        {
                            Id = 5,
                            Code = "COUPON-8VN2D8",
                            Discount = 11.075643775710925m
                        },
                        new
                        {
                            Id = 6,
                            Code = "COUPON-POHM3B",
                            Discount = 24.402851942453100m
                        },
                        new
                        {
                            Id = 7,
                            Code = "COUPON-3L04H2",
                            Discount = 8.458233111650075m
                        },
                        new
                        {
                            Id = 8,
                            Code = "COUPON-W9ZJG9",
                            Discount = 20.301118438119025m
                        },
                        new
                        {
                            Id = 9,
                            Code = "COUPON-RQ9JRM",
                            Discount = 5.291366909874875m
                        },
                        new
                        {
                            Id = 10,
                            Code = "COUPON-5GQURI",
                            Discount = 17.301009691701925m
                        });
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceAfterDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Name = "Rustic Granite Mouse",
                            Photo = "https://picsum.photos/640/480/?image=256",
                            Price = 704.36m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Name = "Incredible Frozen Car",
                            Photo = "https://picsum.photos/640/480/?image=81",
                            Price = 208.49m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Name = "Licensed Concrete Mouse",
                            Photo = "https://picsum.photos/640/480/?image=516",
                            Price = 609.24m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "Incredible Metal Hat",
                            Photo = "https://picsum.photos/640/480/?image=1074",
                            Price = 957.91m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Incredible Soft Gloves",
                            Photo = "https://picsum.photos/640/480/?image=607",
                            Price = 355.38m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Fantastic Fresh Shoes",
                            Photo = "https://picsum.photos/640/480/?image=42",
                            Price = 596.37m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Name = "Awesome Rubber Car",
                            Photo = "https://picsum.photos/640/480/?image=1046",
                            Price = 51.16m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Gorgeous Rubber Pants",
                            Photo = "https://picsum.photos/640/480/?image=1075",
                            Price = 155.44m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            Name = "Generic Plastic Hat",
                            Photo = "https://picsum.photos/640/480/?image=460",
                            Price = 248.28m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Name = "Incredible Metal Soap",
                            Photo = "https://picsum.photos/640/480/?image=1053",
                            Price = 929.37m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            Name = "Practical Plastic Tuna",
                            Photo = "https://picsum.photos/640/480/?image=632",
                            Price = 615.93m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Small Rubber Keyboard",
                            Photo = "https://picsum.photos/640/480/?image=891",
                            Price = 828.65m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Name = "Awesome Concrete Salad",
                            Photo = "https://picsum.photos/640/480/?image=795",
                            Price = 139.97m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Name = "Rustic Soft Soap",
                            Photo = "https://picsum.photos/640/480/?image=409",
                            Price = 907.98m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Incredible Cotton Salad",
                            Photo = "https://picsum.photos/640/480/?image=11",
                            Price = 591.24m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "Fantastic Concrete Chicken",
                            Photo = "https://picsum.photos/640/480/?image=522",
                            Price = 839.29m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Name = "Refined Plastic Bike",
                            Photo = "https://picsum.photos/640/480/?image=348",
                            Price = 890.73m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Refined Wooden Table",
                            Photo = "https://picsum.photos/640/480/?image=374",
                            Price = 855.81m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Name = "Handmade Cotton Table",
                            Photo = "https://picsum.photos/640/480/?image=34",
                            Price = 861.94m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Name = "Practical Granite Bacon",
                            Photo = "https://picsum.photos/640/480/?image=391",
                            Price = 444.11m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Name = "Handcrafted Soft Towels",
                            Photo = "https://picsum.photos/640/480/?image=825",
                            Price = 896.49m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Name = "Handmade Cotton Mouse",
                            Photo = "https://picsum.photos/640/480/?image=754",
                            Price = 936.61m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Name = "Sleek Frozen Chair",
                            Photo = "https://picsum.photos/640/480/?image=923",
                            Price = 202.24m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Name = "Fantastic Rubber Bacon",
                            Photo = "https://picsum.photos/640/480/?image=621",
                            Price = 794.60m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Name = "Fantastic Cotton Chicken",
                            Photo = "https://picsum.photos/640/480/?image=213",
                            Price = 535.25m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Name = "Licensed Granite Gloves",
                            Photo = "https://picsum.photos/640/480/?image=710",
                            Price = 896.56m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Unbranded Metal Ball",
                            Photo = "https://picsum.photos/640/480/?image=903",
                            Price = 260.92m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Name = "Awesome Granite Pizza",
                            Photo = "https://picsum.photos/640/480/?image=61",
                            Price = 347.79m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Name = "Small Soft Keyboard",
                            Photo = "https://picsum.photos/640/480/?image=225",
                            Price = 26.20m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Name = "Awesome Metal Shirt",
                            Photo = "https://picsum.photos/640/480/?image=1000",
                            Price = 476.99m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Name = "Gorgeous Granite Pizza",
                            Photo = "https://picsum.photos/640/480/?image=342",
                            Price = 504.71m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            Name = "Small Cotton Car",
                            Photo = "https://picsum.photos/640/480/?image=32",
                            Price = 362.21m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 8,
                            Name = "Rustic Cotton Towels",
                            Photo = "https://picsum.photos/640/480/?image=424",
                            Price = 393.65m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Name = "Rustic Soft Tuna",
                            Photo = "https://picsum.photos/640/480/?image=268",
                            Price = 593.50m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            Name = "Rustic Wooden Hat",
                            Photo = "https://picsum.photos/640/480/?image=555",
                            Price = 722.53m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            Name = "Small Metal Mouse",
                            Photo = "https://picsum.photos/640/480/?image=465",
                            Price = 265.51m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Name = "Intelligent Frozen Towels",
                            Photo = "https://picsum.photos/640/480/?image=3",
                            Price = 627.67m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Name = "Refined Rubber Computer",
                            Photo = "https://picsum.photos/640/480/?image=582",
                            Price = 98.04m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Name = "Fantastic Metal Soap",
                            Photo = "https://picsum.photos/640/480/?image=299",
                            Price = 121.91m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            Name = "Ergonomic Soft Keyboard",
                            Photo = "https://picsum.photos/640/480/?image=954",
                            Price = 524.24m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 8,
                            Name = "Incredible Granite Soap",
                            Photo = "https://picsum.photos/640/480/?image=120",
                            Price = 715.00m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Name = "Small Steel Chair",
                            Photo = "https://picsum.photos/640/480/?image=626",
                            Price = 253.61m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            Name = "Handcrafted Steel Sausages",
                            Photo = "https://picsum.photos/640/480/?image=510",
                            Price = 116.38m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Name = "Rustic Soft Bike",
                            Photo = "https://picsum.photos/640/480/?image=808",
                            Price = 972.50m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Name = "Incredible Frozen Tuna",
                            Photo = "https://picsum.photos/640/480/?image=1001",
                            Price = 201.48m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Name = "Awesome Soft Fish",
                            Photo = "https://picsum.photos/640/480/?image=720",
                            Price = 481.58m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            Name = "Refined Soft Fish",
                            Photo = "https://picsum.photos/640/480/?image=620",
                            Price = 899.71m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 6,
                            Name = "Practical Wooden Towels",
                            Photo = "https://picsum.photos/640/480/?image=1066",
                            Price = 198.01m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 7,
                            Name = "Unbranded Concrete Gloves",
                            Photo = "https://picsum.photos/640/480/?image=205",
                            Price = 58.02m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 6,
                            Name = "Awesome Rubber Ball",
                            Photo = "https://picsum.photos/640/480/?image=420",
                            Price = 572.60m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            Name = "Handcrafted Plastic Bike",
                            Photo = "https://picsum.photos/640/480/?image=132",
                            Price = 808.76m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 8,
                            Name = "Sleek Cotton Table",
                            Photo = "https://picsum.photos/640/480/?image=1015",
                            Price = 828.89m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Name = "Practical Frozen Soap",
                            Photo = "https://picsum.photos/640/480/?image=451",
                            Price = 163.52m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 4,
                            Name = "Unbranded Granite Gloves",
                            Photo = "https://picsum.photos/640/480/?image=323",
                            Price = 863.16m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Name = "Incredible Concrete Ball",
                            Photo = "https://picsum.photos/640/480/?image=445",
                            Price = 150.51m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 1,
                            Name = "Handcrafted Fresh Sausages",
                            Photo = "https://picsum.photos/640/480/?image=58",
                            Price = 261.41m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 5,
                            Name = "Ergonomic Metal Chair",
                            Photo = "https://picsum.photos/640/480/?image=899",
                            Price = 749.83m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Name = "Unbranded Plastic Towels",
                            Photo = "https://picsum.photos/640/480/?image=957",
                            Price = 519.95m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 8,
                            Name = "Fantastic Soft Shoes",
                            Photo = "https://picsum.photos/640/480/?image=588",
                            Price = 692.04m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 4,
                            Name = "Rustic Wooden Keyboard",
                            Photo = "https://picsum.photos/640/480/?image=512",
                            Price = 292.80m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            Name = "Ergonomic Concrete Table",
                            Photo = "https://picsum.photos/640/480/?image=1052",
                            Price = 335.63m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 3,
                            Name = "Ergonomic Plastic Bike",
                            Photo = "https://picsum.photos/640/480/?image=468",
                            Price = 744.52m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            Name = "Incredible Plastic Chair",
                            Photo = "https://picsum.photos/640/480/?image=772",
                            Price = 952.45m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            Name = "Ergonomic Granite Gloves",
                            Photo = "https://picsum.photos/640/480/?image=716",
                            Price = 906.49m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            Name = "Tasty Granite Sausages",
                            Photo = "https://picsum.photos/640/480/?image=1011",
                            Price = 714.82m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            Name = "Fantastic Soft Mouse",
                            Photo = "https://picsum.photos/640/480/?image=311",
                            Price = 670.91m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 6,
                            Name = "Gorgeous Fresh Pizza",
                            Photo = "https://picsum.photos/640/480/?image=919",
                            Price = 54.10m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 1,
                            Name = "Practical Plastic Keyboard",
                            Photo = "https://picsum.photos/640/480/?image=331",
                            Price = 949.87m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 8,
                            Name = "Fantastic Wooden Tuna",
                            Photo = "https://picsum.photos/640/480/?image=181",
                            Price = 989.36m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 4,
                            Name = "Refined Frozen Table",
                            Photo = "https://picsum.photos/640/480/?image=432",
                            Price = 756.68m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 4,
                            Name = "Small Concrete Towels",
                            Photo = "https://picsum.photos/640/480/?image=756",
                            Price = 182.76m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 5,
                            Name = "Unbranded Plastic Computer",
                            Photo = "https://picsum.photos/640/480/?image=220",
                            Price = 529.40m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            Name = "Handcrafted Plastic Ball",
                            Photo = "https://picsum.photos/640/480/?image=259",
                            Price = 459.93m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 5,
                            Name = "Practical Rubber Shoes",
                            Photo = "https://picsum.photos/640/480/?image=442",
                            Price = 348.24m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 7,
                            Name = "Generic Metal Cheese",
                            Photo = "https://picsum.photos/640/480/?image=989",
                            Price = 245.27m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 5,
                            Name = "Awesome Soft Pants",
                            Photo = "https://picsum.photos/640/480/?image=1060",
                            Price = 521.48m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 3,
                            Name = "Licensed Fresh Chips",
                            Photo = "https://picsum.photos/640/480/?image=865",
                            Price = 577.85m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 6,
                            Name = "Gorgeous Rubber Ball",
                            Photo = "https://picsum.photos/640/480/?image=651",
                            Price = 215.37m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 4,
                            Name = "Gorgeous Wooden Towels",
                            Photo = "https://picsum.photos/640/480/?image=641",
                            Price = 29.09m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            Name = "Tasty Cotton Soap",
                            Photo = "https://picsum.photos/640/480/?image=469",
                            Price = 96.84m
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 1,
                            Name = "Intelligent Soft Gloves",
                            Photo = "https://picsum.photos/640/480/?image=575",
                            Price = 838.03m
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 4,
                            Name = "Gorgeous Steel Shoes",
                            Photo = "https://picsum.photos/640/480/?image=1013",
                            Price = 398.62m
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 8,
                            Name = "Fantastic Rubber Salad",
                            Photo = "https://picsum.photos/640/480/?image=600",
                            Price = 401.35m
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 5,
                            Name = "Sleek Cotton Computer",
                            Photo = "https://picsum.photos/640/480/?image=188",
                            Price = 582.18m
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 2,
                            Name = "Small Wooden Pants",
                            Photo = "https://picsum.photos/640/480/?image=306",
                            Price = 443.10m
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            Name = "Sleek Granite Table",
                            Photo = "https://picsum.photos/640/480/?image=712",
                            Price = 331.50m
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 1,
                            Name = "Unbranded Frozen Sausages",
                            Photo = "https://picsum.photos/640/480/?image=963",
                            Price = 672.66m
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 3,
                            Name = "Practical Metal Soap",
                            Photo = "https://picsum.photos/640/480/?image=202",
                            Price = 219.74m
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 5,
                            Name = "Awesome Steel Ball",
                            Photo = "https://picsum.photos/640/480/?image=749",
                            Price = 918.19m
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 7,
                            Name = "Gorgeous Fresh Chips",
                            Photo = "https://picsum.photos/640/480/?image=910",
                            Price = 503.63m
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 1,
                            Name = "Rustic Wooden Sausages",
                            Photo = "https://picsum.photos/640/480/?image=477",
                            Price = 132.26m
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 5,
                            Name = "Unbranded Steel Chicken",
                            Photo = "https://picsum.photos/640/480/?image=1082",
                            Price = 471.15m
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 7,
                            Name = "Handcrafted Soft Chicken",
                            Photo = "https://picsum.photos/640/480/?image=46",
                            Price = 879.43m
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 7,
                            Name = "Unbranded Granite Chicken",
                            Photo = "https://picsum.photos/640/480/?image=296",
                            Price = 595.30m
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 2,
                            Name = "Sleek Plastic Pants",
                            Photo = "https://picsum.photos/640/480/?image=489",
                            Price = 230.57m
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 5,
                            Name = "Rustic Fresh Bacon",
                            Photo = "https://picsum.photos/640/480/?image=294",
                            Price = 151.97m
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 4,
                            Name = "Intelligent Cotton Pizza",
                            Photo = "https://picsum.photos/640/480/?image=336",
                            Price = 634.28m
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 4,
                            Name = "Handmade Granite Soap",
                            Photo = "https://picsum.photos/640/480/?image=512",
                            Price = 602.29m
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 3,
                            Name = "Licensed Fresh Mouse",
                            Photo = "https://picsum.photos/640/480/?image=16",
                            Price = 523.55m
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 7,
                            Name = "Tasty Fresh Car",
                            Photo = "https://picsum.photos/640/480/?image=341",
                            Price = 649.34m
                        });
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Order", b =>
                {
                    b.HasOne("ReboteqTask.Core.Entities.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("ReboteqTask.Core.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReboteqTask.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Product", b =>
                {
                    b.HasOne("ReboteqTask.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReboteqTask.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
